# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\toolsbox.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_toolsbox(object):
    def setupUi(self, toolsbox):
        toolsbox.setObjectName("toolsbox")
        toolsbox.resize(577, 571)
        self.horizontalLayout = QtWidgets.QHBoxLayout(toolsbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.function_select = QtWidgets.QListWidget(toolsbox)
        self.function_select.setMaximumSize(QtCore.QSize(100, 16777215))
        self.function_select.setObjectName("function_select")
        item = QtWidgets.QListWidgetItem()
        self.function_select.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.function_select.addItem(item)
        self.horizontalLayout.addWidget(self.function_select)
        self.stackedWidget = QtWidgets.QStackedWidget(toolsbox)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ipconvert_str2num_input = QtWidgets.QLineEdit(self.groupBox)
        self.ipconvert_str2num_input.setObjectName("ipconvert_str2num_input")
        self.gridLayout.addWidget(self.ipconvert_str2num_input, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.ipconvert_str2num_run = QtWidgets.QPushButton(self.groupBox)
        self.ipconvert_str2num_run.setObjectName("ipconvert_str2num_run")
        self.gridLayout.addWidget(self.ipconvert_str2num_run, 2, 1, 1, 1)
        self.ipconvert_str2num_output = QtWidgets.QLineEdit(self.groupBox)
        self.ipconvert_str2num_output.setEnabled(True)
        self.ipconvert_str2num_output.setReadOnly(True)
        self.ipconvert_str2num_output.setObjectName("ipconvert_str2num_output")
        self.gridLayout.addWidget(self.ipconvert_str2num_output, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.ipconvert_num2str_output = QtWidgets.QLineEdit(self.groupBox_2)
        self.ipconvert_num2str_output.setEnabled(True)
        self.ipconvert_num2str_output.setReadOnly(True)
        self.ipconvert_num2str_output.setObjectName("ipconvert_num2str_output")
        self.gridLayout_2.addWidget(self.ipconvert_num2str_output, 1, 1, 1, 1)
        self.ipconvert_num2str_run = QtWidgets.QPushButton(self.groupBox_2)
        self.ipconvert_num2str_run.setObjectName("ipconvert_num2str_run")
        self.gridLayout_2.addWidget(self.ipconvert_num2str_run, 2, 1, 1, 1)
        self.ipconvert_num2str_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.ipconvert_num2str_input.setObjectName("ipconvert_num2str_input")
        self.gridLayout_2.addWidget(self.ipconvert_num2str_input, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.jsonformat_text = QtWidgets.QPlainTextEdit(self.page_2)
        self.jsonformat_text.setObjectName("jsonformat_text")
        self.verticalLayout_2.addWidget(self.jsonformat_text)
        self.jsonformat_run = QtWidgets.QPushButton(self.page_2)
        self.jsonformat_run.setObjectName("jsonformat_run")
        self.verticalLayout_2.addWidget(self.jsonformat_run)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(toolsbox)
        self.stackedWidget.setCurrentIndex(1)
        self.function_select.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(toolsbox)

    def retranslateUi(self, toolsbox):
        _translate = QtCore.QCoreApplication.translate
        toolsbox.setWindowTitle(_translate("toolsbox", "Dialog"))
        __sortingEnabled = self.function_select.isSortingEnabled()
        self.function_select.setSortingEnabled(False)
        item = self.function_select.item(0)
        item.setText(_translate("toolsbox", "IP格式转换"))
        item = self.function_select.item(1)
        item.setText(_translate("toolsbox", "JSON美化"))
        self.function_select.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("toolsbox", "字符串IP转整数IP"))
        self.label.setText(_translate("toolsbox", "字符串IP"))
        self.label_2.setText(_translate("toolsbox", "整数IP"))
        self.ipconvert_str2num_run.setText(_translate("toolsbox", "转换"))
        self.groupBox_2.setTitle(_translate("toolsbox", "整数IP转字符串IP"))
        self.label_3.setText(_translate("toolsbox", "整数IP"))
        self.label_4.setText(_translate("toolsbox", "字符串IP"))
        self.ipconvert_num2str_run.setText(_translate("toolsbox", "转换"))
        self.jsonformat_run.setText(_translate("toolsbox", "格式化"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    toolsbox = QtWidgets.QDialog()
    ui = Ui_toolsbox()
    ui.setupUi(toolsbox)
    toolsbox.show()
    sys.exit(app.exec_())

